name: adf_cuidapet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # sdk: '>=2.18.1 <3.0.0'
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  flutter_modular: 5.0.3

  mobx: 2.1.3
  flutter_mobx: 2.0.6+5
  asuka: 2.0.1+3
  dio: 4.0.6
  flutter_screenutil: 5.6.0
  firebase_core: 2.3.0
  firebase_remote_config: 3.0.6
  firebase_analytics: 10.0.6
  firebase_auth: 4.1.5
  firebase_messaging: 14.1.3

  flutter_dotenv: 5.0.2
  logger: 1.1.0

  flutter_secure_storage: 6.1.0
  shared_preferences: 2.0.15

  validatorless: 1.2.3
  
  google_sign_in: 6.0.2
  flutter_facebook_auth: 5.0.6
  flutter_typeahead: 4.1.1
  # google_place: 0.4.7
  # flutter_google_places_sdk: ^0.3.2+6
  google_maps_flutter: 2.2.5

  # -------SQLITE-------
  sqflite: 2.2.2
  synchronized: 3.0.0+3
  
  path: 1.8.2
  # Está fixado na versão 1.8.2 por causa do flutter_test

  # -------SQLITE-------

  # -------GEO-------
  geocoding: 2.0.5
  geolocator: 9.0.2
  intl: ^0.17.0
  url_launcher: ^6.1.10

  google_places:
   git:
    url: https://github.com/caneto/google_place.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.1.1
  build_runner: 2.3.2

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - .env
      #   - images/a_dot_ham.jpeg



  fonts:
    - family: Cuidapeticons
      fonts:
        - asset: assets/fonts/Cuidapeticons.ttf

